<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..7uNotq' shared service.

return $this->privates['.service_locator..7uNotq'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('container' => function (): \Symfony\Component\DependencyInjection\ContainerBuilder {
    return ($this->privates['.errored..service_locator..7uNotq.Symfony\Component\DependencyInjection\ContainerBuilder'] ?? $this->load('getContainerBuilderService.php'));
}));
