<?php
/**
 * Created by PhpStorm.
 * User: JorgePc
 * Date: 06/09/2018
 * Time: 19:23
 */

namespace App\Domain\Anuncios\Domain\Component\Components;

use App\Domain\Anuncios\Domain\Component\Components\ComponentsVO\ComponentAncho;
use App\Domain\Anuncios\Domain\Component\Components\ComponentsVO\ComponentAlto;
use App\Domain\Anuncios\Domain\Component\Components\ComponentsVO\ComponentPosicion;
use App\Domain\Anuncios\Domain\Component\Components\ComponentsVO\ComponentNombre;

use App\Domain\Anuncios\Domain\Component\Component;
use App\Domain\Anuncios\Domain\Component\Components\FileComponentVO\TextFile;

class ComponentFile extends Component
{

    private $ancho;
    private $alto;
    private $position;
    public function __construct($textFile,$ancho,$alto,$position,$nombre)
    {
        $textFile = new TextFile($textFile);
        $this->textFile = $textFile->getText();
        $this->position=new ComponentPosicion($position);
        $this->ancho=new ComponentAncho($ancho);
        $this->alto=new ComponentAlto($alto);
        $this->nombre = new ComponentNombre($nombre);
    }
    
    public static function createComponent($componentType, $componentObject)
    {
        return new self ($componentObject['text'],
            $componentObject['ancho'],
            $componentObject['alto'],
            $componentObject['position'],
            $componentObject['nombre']);
    }

    protected static function constructComponent($componentObject)
    {
        return new self (
            $componentObject['text'],
            $componentObject['ancho'],
            $componentObject['alto'],
            $componentObject['position'],
            $componentObject['name']);;
    }
    public function getComponent()
    {
        return $this;
    }
    
    
    public function getAncho()
    {
        $this->ancho; // TODO: Change the autogenerated stub
    }
    
    public function getAlto()
    {
        $this->alto; // TODO: Change the autogenerated stub
    }
    
    public function getPosition()
    {
        $this->position; // TODO: Change the autogenerated stub
    }
}