version: '3'
services:
  apache-php:
    build:
      dockerfile: .docker/apache/Dockerfile
      context: ./
    container_name: apache_container
    ports:
    - 8001:80
    volumes:
    #    - .docker/config/vhosts:/etc/apache2/sites-enabled
    - .:/app
  #    depends_on:
  #    - php_service

  mysql_s:
    image: mysql:5.7
    container_name: mysql_container
    #    volumes:
    #    - .docker/data/db:/var/lib/mysql
    environment:
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_ALLOW_EMPTY_PASSWORD

#  php_service:
#    build: .docker/php
#    container_name: php_container
#    volumes:
#    - .:/home/wwwroot/sf4
#    depends_on:
#    - mysql_service