<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEP8Om89\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEP8Om89/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEP8Om89.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerEP8Om89\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerEP8Om89\srcProdProjectContainer(array(
    'container.build_hash' => 'EP8Om89',
    'container.build_id' => 'b3be2db7',
    'container.build_time' => 1537271235,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEP8Om89');
