<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxoZ68P\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxoZ68P/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNxoZ68P.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerNxoZ68P\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerNxoZ68P\srcProdProjectContainer(array(
    'container.build_hash' => 'NxoZ68P',
    'container.build_id' => '5e17a614',
    'container.build_time' => 1537783903,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxoZ68P');
