<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCwOLB04\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCwOLB04/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCwOLB04.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerCwOLB04\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerCwOLB04\srcProdProjectContainer(array(
    'container.build_hash' => 'CwOLB04',
    'container.build_id' => 'c90646de',
    'container.build_time' => 1537198057,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCwOLB04');
