<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bxfMTph' shared service.

return $this->privates['.service_locator.bxfMTph'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('application' => function (): \Symfony\Component\Console\Application {
    return ($this->privates['.errored..service_locator.bxfMTph.Symfony\Component\Console\Application'] ?? $this->load('getApplicationService.php'));
}));
