<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'anuncio_repository_doctrine' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\persistence\\lib\\Doctrine\\Common\\Persistence\\ObjectRepository.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\collections\\lib\\Doctrine\\Common\\Collections\\Selectable.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\EntityRepository.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\doctrine-bundle\\Repository\\ServiceEntityRepositoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\doctrine-bundle\\Repository\\ServiceEntityRepository.php';
include_once $this->targetDirs[3].'\\src\\Domain\\Anuncios\\Domain\\AnuncioDomain\\AnuncioRepository.php';
include_once $this->targetDirs[3].'\\src\\Domain\\Anuncios\\Persistance\\AnuncioPersistance.php';

return $this->privates['anuncio_repository_doctrine'] = new \App\Domain\Anuncios\Persistance\AnuncioPersistance(($this->services['doctrine'] ?? $this->getDoctrineService()), 'App\\Domain\\Anuncios\\Domain\\AnuncioDomain\\Anuncio', ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
