anuncio_create:
    path:     /
    defaults: { _controller: anuncio.controller:create }
    methods:    [POST]

anuncio_modify:
    path:     /modify/
    defaults: { _controller: anuncio.controller:modify }
    methods:    [POST]
