<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.tactician.command.debug' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\league\\tactician-bundle\\src\\Command\\DebugCommand.php';

return $this->services['console.command.public_alias.tactician.command.debug'] = new \League\Tactician\Bundle\Command\DebugCommand(array('default' => array('App\\Domain\\Anuncios\\UseCases\\CreateAnuncio\\AnuncioCommand' => 'App\\Domain\\Anuncios\\UseCases\\CreateAnuncio\\CreateAnuncioHandler')));
