<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator..7uNotq.Symfony\Component\DependencyInjection\ContainerBuilder' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator..7uNotq": it references class "Symfony\\Component\\DependencyInjection\\ContainerBuilder" but no such service exists. Try changing the type-hint to one of its parents: interface "Symfony\\Component\\DependencyInjection\\ContainerInterface", or interface "Psr\\Container\\ContainerInterface".');
