<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'event_domain.publisher' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Domain\\Anuncios\\Domain\\EventPublisher.php';
include_once $this->targetDirs[3].'\\src\\IO\\Events\\DomainEventPublisherRabbitMq.php';

return $this->privates['event_domain.publisher'] = new \App\IO\Events\DomainEventPublisherRabbitMq();
