<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'message_bus' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Middleware\\MiddlewareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Middleware\\LoggingMiddleware.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Asynchronous\\Routing\\SenderLocatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Asynchronous\\Routing\\SenderLocator.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\EnvelopeAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Asynchronous\\Middleware\\SendMessageMiddleware.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Handler\\Locator\\HandlerLocatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Handler\\Locator\\ContainerHandlerLocator.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\Middleware\\HandleMessageMiddleware.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\MessageBusInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\MessageBus.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\messenger\\TraceableMessageBus.php';

return $this->services['message_bus'] = new \Symfony\Component\Messenger\TraceableMessageBus(new \Symfony\Component\Messenger\MessageBus(array(0 => new \Symfony\Component\Messenger\Middleware\LoggingMiddleware(($this->privates['logger'] ?? $this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())), 1 => new \Symfony\Component\Messenger\Asynchronous\Middleware\SendMessageMiddleware(new \Symfony\Component\Messenger\Asynchronous\Routing\SenderLocator(new \Symfony\Component\DependencyInjection\ServiceLocator(array()), array()), array()), 2 => new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\Locator\ContainerHandlerLocator(new \Symfony\Component\DependencyInjection\ServiceLocator(array()))))));
