<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFNGPaP9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFNGPaP9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFNGPaP9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFNGPaP9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFNGPaP9\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FNGPaP9',
    'container.build_id' => 'd073a66e',
    'container.build_time' => 1537198079,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFNGPaP9');
