<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRBIOsT5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRBIOsT5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRBIOsT5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRBIOsT5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRBIOsT5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'RBIOsT5',
    'container.build_id' => 'f6b82e90',
    'container.build_time' => 1537799899,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRBIOsT5');
