<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container11O9FF2\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container11O9FF2/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container11O9FF2.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container11O9FF2\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container11O9FF2\srcDevDebugProjectContainer(array(
    'container.build_hash' => '11O9FF2',
    'container.build_id' => '0f420e25',
    'container.build_time' => 1537279884,
), __DIR__.\DIRECTORY_SEPARATOR.'Container11O9FF2');
