<?php

namespace Proxies\__CG__\App\Domain\Anuncios\Domain\Component\Components;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ComponentVideo extends \App\Domain\Anuncios\Domain\Component\Components\ComponentVideo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'componentId', 'ancho', 'alto', 'position', '' . "\0" . 'App\\Domain\\Anuncios\\Domain\\Component\\Components\\ComponentVideo' . "\0" . 'videoFormat', '' . "\0" . 'App\\Domain\\Anuncios\\Domain\\Component\\Components\\ComponentVideo' . "\0" . 'videoUrl', '' . "\0" . 'App\\Domain\\Anuncios\\Domain\\Component\\Components\\ComponentVideo' . "\0" . 'videoWeight', 'anuncioId', 'nombre'];
        }

        return ['__isInitialized__', 'componentId', 'ancho', 'alto', 'position', '' . "\0" . 'App\\Domain\\Anuncios\\Domain\\Component\\Components\\ComponentVideo' . "\0" . 'videoFormat', '' . "\0" . 'App\\Domain\\Anuncios\\Domain\\Component\\Components\\ComponentVideo' . "\0" . 'videoUrl', '' . "\0" . 'App\\Domain\\Anuncios\\Domain\\Component\\Components\\ComponentVideo' . "\0" . 'videoWeight', 'anuncioId', 'nombre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ComponentVideo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getComponentId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getComponentId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentId', []);

        return parent::getComponentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setComponentId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComponentId', [$id]);

        return parent::setComponentId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosicion', []);

        return parent::getPosicion();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function setAncho($ancho)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAncho', [$ancho]);

        return parent::setAncho($ancho);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlto($alto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlto', [$alto]);

        return parent::setAlto($alto);
    }

    /**
     * {@inheritDoc}
     */
    public function setComponentPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComponentPosition', [$position]);

        return parent::setComponentPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getAncho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAncho', []);

        return parent::getAncho();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlto', []);

        return parent::getAlto();
    }

    /**
     * {@inheritDoc}
     */
    public function getComponentPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentPosition', []);

        return parent::getComponentPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function getComponent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponent', []);

        return parent::getComponent();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnuncioId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnuncioId', []);

        return parent::getAnuncioId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnuncioId($anuncioId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnuncioId', [$anuncioId]);

        return parent::setAnuncioId($anuncioId);
    }

}
